import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <meta charSet="utf-8" />
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="images/fevicon.png" type="image/gif" />
          <meta name="keywords" content="" />
          <meta name="description" content="" />
          <meta name="author" content="" />
          <title>PROXD</title>
          <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

          <link
            href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap"
            rel="stylesheet"
          />

          <link href="css/font-awesome.min.css" rel="stylesheet" />
          <link href="css/style.css" rel="stylesheet" />
          <link href="css/responsive.css" rel="stylesheet" />

          <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
          <link
            href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap"
            rel="stylesheet"
          />
          <link href="css/font-awesome.min.css" rel="stylesheet" />
          <link href="css/style.css" rel="stylesheet" />
          <link href="css/responsive.css" rel="stylesheet" />
          {children}
          <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>

          <script src="js/jquery-3.4.1.min.js"></script>
          <script src="js/custom.js"></script>
        </main>
      </body>
    </html>
  );
}
